"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-24

Bootstrap migration: creates the full schema from the SQLAlchemy metadata. Subsequent
schema changes should use autogenerated, explicit migrations.
"""
from __future__ import annotations

from collections.abc import Sequence

import app.models  # noqa: F401  (registers all tables on Base.metadata)
from alembic import op
from app.db.base import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
